name: Playground for Requests

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  build-playground:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]

    - name: Set up Git configuration
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Clone the gh-pages branch
      run: |
        git clone --single-branch --branch gh-pages https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages

    - name: define Qualified Path
      run: |
        TARGET_DIR="pr/${{ github.head_ref}}/${GITHUB_SHA}"
        echo "TARGET_DIR=$TARGET_DIR" >> $GITHUB_ENV

    - name: Run Playground Script
      run: ./scripts/playground.sh $TARGET_DIR
      # this produces a dist/$TARGET_DIR folder. we want to move this to gh-pages/$TARGET_DIR

    - name: move dist folder
      run: |
        mkdir -p "gh-pages/$TARGET_DIR"
        mv "dist/$TARGET_DIR" $(dirname "gh-pages/$TARGET_DIR")

    - name: Commit and push changes
      run: |
        cd gh-pages
        git add .
        git commit -m "Deploying state of PR ${{ github.pr_number}} from ${{ github.head_ref}}"
        git push origin gh-pages --force

    - name: Create new Comment with Badge under PR
      uses: actions/github-script@v6
      with:
        script: |
          const playgroundURL= `https://playground.wordpress.net/?blueprint-url=https://raw.githubusercontent.com/IONOS-WordPress/cfhack2024-wp-react-jsonschema-form/gh-pages/${TARGET_DIR}/playground.json`;
          const badge = `https://img.shields.io/static/v1?logo=wordpress&logoColor=white&label=wp-playground&message=review%20using%20playground&color=41439a`;
          const comment = `[![${badge}](${badge})](${playgroundURL})`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });


